### ISSUE TITLE
URL partagée

### ISSUE THREAD

**Issue by Bibi56** [GeoOSM/backend_nodejs#4]
Déjà le lien "coller dans le presse-papier" devrait être le premier. Et non au petit bonheur la chance entre deux réseaux sociaux.
Ensuite le nom du serveur est france.geocameroun.xyz et non geosm.openstreetmap.fr.
Une restriction technique ?

**Comment by TANK2003** [comment]
Le lien du partage est resolu.

Bien vu pour les bouttons de partages !
