### ISSUE TITLE
Prison

### ISSUE THREAD

**Issue by gendy54** [GeoOSM/backend_nodejs#5]
Hello,

Dans la géothématique Service public>sécurité, il y a un thème Gendarmerie qui renvoie vers un extract d'amenity=prison en plus d'être en doublon de Police & Gendarmerie

**Comment by TANK2003** [comment]
Hi !

Effectivement, j'ai supprimé la couche Gendarmerie qui ne refletait pas les gendarmeries.

La couche prison se trouvant dans la géothématique Sureté : http://geosm.openstreetmap.fr//map?share=data&path=407,64,49

Je suis preneur de toute suggestion pour l'ordonnance des couches. La grande majorité a été faite par Jean Louis Zimmerman.
