### ISSUE TITLE
missing amenity=school 

### ISSUE THREAD

**Issue by Stefal** [GeoOSM/backend_nodejs#6]
en:
Some schools are missing on the educational layers. This one for example:
https://www.openstreetmap.org/way/114655774
http://geosm.openstreetmap.fr//map?share=state&nbre=3&path=-148757.2434,5955356.0791,18&path0=data,647,95,14&path1=data,649,95,14&path2=data,655,96,14

It seems related to node vs polygon.

fr:
Il manque beaucoup d'école lorsqu'on coche les items "éducation". J'ai l'impression que geosm ne reconnait pas les écoles sous forme de polygones.
exemples : 
https://www.openstreetmap.org/way/114655774
http://geosm.openstreetmap.fr//map?share=state&nbre=3&path=-148757.2434,5955356.0791,18&path0=data,647,95,14&path1=data,649,95,14&path2=data,655,96,14

**Comment by TANK2003** [comment]
Pour les ponctuels on recherche dans les polygonnes et les ponctuels. Ce manque vient plus tôt des tags utilisés.

Les couches de la sous thématique "Education" sont :
- **school:FR='lycée'** pour les lycées
- **school:FR='collège'** pour les collèges
- **school:FR='maternelle'** pour écoles maternelles
- **amenity='university'** pour les unniversités

Or l'École primaire privée Sainte-Jeanne d'Arc (https://www.openstreetmap.org/way/114655774) a school:FR='primaire'

Il faudrait le rajouter dans la requète d'une des couches existantent ou créer une autre ?

**Comment by Stefal** [comment]
**school:FR=primaire** englobe école maternelle et école élémentaire.

Donc j'imagine plutôt ça : 
+ **school:FR=primaire** pour la section "école primaire", qui englobe **school:FR=primaire**, **school:FR=maternelle** et **school:FR=élémentaire**
+ **school:FR=collège** pour les collèges

etc...

**Comment by TANK2003** [comment]
Nickel, j'ai crée une couche "Ecole primaire" et l'école primaire Sainte-jeanne d'Arc y est à present : http://geosm.openstreetmap.fr//map?share=state&nbre=3&path=-148736.5185,5955401.3307,19&path0=data,649,95,14&path1=data,655,96,14&path2=data,670,96,14

Merci du retour
