### ISSUE TITLE
kindergarten in educational items ?

### ISSUE THREAD

**Issue by Stefal** [GeoOSM/backend_nodejs#7]
fr:
Oui, je sais qu'on a du mal à se sortir de cette discussion sur la façon de tagger les écoles maternelles, mais ce qui est certain, c'est que
`amenity=kindergarten` + `kindergarten:FR=*`
Ne devrait pas être dans la catégorie "éducation".
Exemple pour une "halte garderie" qui se retrouve dans "enseignement primaire" : 
http://geosm.openstreetmap.fr//map?share=state&nbre=1&path=-159297.8966,5937334.5170,19&path0=data,647,95,14

**Comment by TANK2003** [comment]
Cette couche etait dans un bloc à trier, je profite pour la supprimer.
